-- MySQL Script generated by MySQL Workbench
-- Sun Mar 17 19:20:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema viviendaAlquiler
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `viviendaAlquiler` ;

-- -----------------------------------------------------
-- Schema viviendaAlquiler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viviendaAlquiler` DEFAULT CHARACTER SET utf8 ;
USE `viviendaAlquiler` ;

-- -----------------------------------------------------
-- Table `viviendaAlquiler`.`INQUILINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendaAlquiler`.`INQUILINO` (
  `Id_Inquilino` INT NOT NULL,
  `Nombre_1` VARCHAR(10) NOT NULL,
  `Nombre_2` VARCHAR(10) NULL,
  `Apellido_1` VARCHAR(10) NOT NULL,
  `Apellido_2` VARCHAR(10) NOT NULL,
  `Edad` INT NOT NULL,
  `INE` VARCHAR(45) NOT NULL,
  `TEL_lada` INT NOT NULL,
  `TEL_digito` INT NOT NULL,
  `Com_nomina` INT NULL,
  PRIMARY KEY (`Id_Inquilino`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Id_Propietario_UNIQUE` ON `viviendaAlquiler`.`INQUILINO` (`Id_Inquilino` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `viviendaAlquiler`.`ALQUILER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendaAlquiler`.`ALQUILER` (
  `Id_Alquiler` INT NOT NULL,
  `FECON_inicio` DATE NOT NULL,
  `FECON_fin` DATE NOT NULL,
  `EDOCON_disponible` VARCHAR(2) NOT NULL,
  `EDOCON_alquilado` VARCHAR(2) NOT NULL,
  `INQUILINO_Id_Inquilino` INT NOT NULL,
  PRIMARY KEY (`Id_Alquiler`, `INQUILINO_Id_Inquilino`),
  CONSTRAINT `fk_ALQUILER_INQUILINO1`
    FOREIGN KEY (`INQUILINO_Id_Inquilino`)
    REFERENCES `viviendaAlquiler`.`INQUILINO` (`Id_Inquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ALQUILER_INQUILINO1_idx` ON `viviendaAlquiler`.`ALQUILER` (`INQUILINO_Id_Inquilino` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `viviendaAlquiler`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendaAlquiler`.`VIVIENDA` (
  `Id_Vivienda` INT NOT NULL,
  `DIR_calle` VARCHAR(20) NOT NULL,
  `DIR_num.ext` INT NOT NULL,
  `DIR_num.int` INT NULL,
  `DIR_colonia` VARCHAR(20) NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `Metros_Cuadrados` INT NULL,
  `Num.Habitaciones` INT NOT NULL,
  `SER_tienda` INT NULL,
  `SER_restaurant` INT NULL,
  `SER_insumos` INT NULL,
  `ALQUILER_Id_Alquiler` INT NOT NULL,
  PRIMARY KEY (`Id_Vivienda`, `ALQUILER_Id_Alquiler`),
  CONSTRAINT `fk_VIVIENDA_ALQUILER1`
    FOREIGN KEY (`ALQUILER_Id_Alquiler`)
    REFERENCES `viviendaAlquiler`.`ALQUILER` (`Id_Alquiler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Id_Vivienda_UNIQUE` ON `viviendaAlquiler`.`VIVIENDA` (`Id_Vivienda` ASC) VISIBLE;

CREATE INDEX `fk_VIVIENDA_ALQUILER1_idx` ON `viviendaAlquiler`.`VIVIENDA` (`ALQUILER_Id_Alquiler` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `viviendaAlquiler`.`PROPIETARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendaAlquiler`.`PROPIETARIO` (
  `Id_Propietario` INT NOT NULL,
  `Nombre_1` VARCHAR(10) NOT NULL,
  `Nombre_2` VARCHAR(10) NULL,
  `Apellido_1` VARCHAR(10) NOT NULL,
  `Apellido_2` VARCHAR(10) NOT NULL,
  `Edad` INT NOT NULL,
  `DOM_num.ext` INT NOT NULL,
  `DOM_calle` VARCHAR(20) NOT NULL,
  `DOM_num.int` INT NULL,
  `DOM_colonia` VARCHAR(20) NOT NULL,
  `INE` VARCHAR(45) NOT NULL,
  `TEL_lada` INT NOT NULL,
  `TEL_digito` INT NOT NULL,
  `Folio_escrituras` VARCHAR(45) NULL,
  `VIVIENDA_Id_Vivienda` INT NOT NULL,
  PRIMARY KEY (`Id_Propietario`, `VIVIENDA_Id_Vivienda`),
  CONSTRAINT `fk_PROPIETARIO_VIVIENDA`
    FOREIGN KEY (`VIVIENDA_Id_Vivienda`)
    REFERENCES `viviendaAlquiler`.`VIVIENDA` (`Id_Vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Id_Propietario_UNIQUE` ON `viviendaAlquiler`.`PROPIETARIO` (`Id_Propietario` ASC) VISIBLE;

CREATE INDEX `fk_PROPIETARIO_VIVIENDA_idx` ON `viviendaAlquiler`.`PROPIETARIO` (`VIVIENDA_Id_Vivienda` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
